title: Cryptography Wiki
description: A personal wiki about cryptography related topics
theme: just-the-docs

url: https://cryptographywiki.com

aux_links:
  Template Repository: https://github.com/timglitch0/cryptographywiki.com
